var express = require("express");
var app = express();
var router = require("./routers/router");
var bodyParser = require("body-parser");
const cors = require("cors");
const port = process.env.PORT || 5000;
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(router);
app.listen(port, console.log(`Server started on port ${port}`));
